# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\collecte.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(621, 487)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.txtDate = QtWidgets.QLabel(Dialog)
        self.txtDate.setStyleSheet("font-size: 60px;\n"
"font-weight: bold;\n"
"color: rgb(85, 170, 0);")
        self.txtDate.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDate.setObjectName("txtDate")
        self.gridLayout.addWidget(self.txtDate, 0, 0, 1, 2)
        self.tabSeances = QtWidgets.QTabWidget(Dialog)
        self.tabSeances.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabSeances.setElideMode(QtCore.Qt.ElideLeft)
        self.tabSeances.setDocumentMode(False)
        self.tabSeances.setTabsClosable(False)
        self.tabSeances.setTabBarAutoHide(False)
        self.tabSeances.setObjectName("tabSeances")
        self.tabSeance1 = QtWidgets.QWidget()
        self.tabSeance1.setObjectName("tabSeance1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabSeance1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabLabos = QtWidgets.QTabWidget(self.tabSeance1)
        self.tabLabos.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabLabos.setObjectName("tabLabos")
        self.tabLabo1 = QtWidgets.QWidget()
        self.tabLabo1.setObjectName("tabLabo1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabLabo1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txtSeance = QtWidgets.QLabel(self.tabLabo1)
        self.txtSeance.setStyleSheet("font-size: 40px;\n"
"font-weight: bold;\n"
"color: rgb(255, 85, 0);")
        self.txtSeance.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSeance.setObjectName("txtSeance")
        self.gridLayout_3.addWidget(self.txtSeance, 0, 0, 1, 1)
        self.txtLabo = QtWidgets.QLabel(self.tabLabo1)
        self.txtLabo.setStyleSheet("font-size: 40px;\n"
"font-weight: bold;\n"
"color: rgb(255, 0, 127);")
        self.txtLabo.setAlignment(QtCore.Qt.AlignCenter)
        self.txtLabo.setObjectName("txtLabo")
        self.gridLayout_3.addWidget(self.txtLabo, 0, 1, 1, 1)
        self.lblArb = QtWidgets.QLabel(self.tabLabo1)
        self.lblArb.setStyleSheet("font-weight: bold;\n"
"font-size: 12pt;")
        self.lblArb.setAlignment(QtCore.Qt.AlignCenter)
        self.lblArb.setObjectName("lblArb")
        self.gridLayout_3.addWidget(self.lblArb, 1, 0, 1, 2)
        self.treeWidget = QtWidgets.QTreeWidget(self.tabLabo1)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout_3.addWidget(self.treeWidget, 2, 0, 1, 2)
        self.tabLabos.addTab(self.tabLabo1, "")
        self.gridLayout_2.addWidget(self.tabLabos, 0, 0, 1, 2)
        self.tabSeances.addTab(self.tabSeance1, "")
        self.gridLayout.addWidget(self.tabSeances, 1, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.tabSeances.setCurrentIndex(0)
        self.tabLabos.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.txtDate.setText(_translate("Dialog", "2023-05-28"))
        self.txtSeance.setText(_translate("Dialog", "Séance xx"))
        self.txtLabo.setText(_translate("Dialog", "Labo xx"))
        self.lblArb.setText(_translate("Dialog", "Arborescence"))
        self.tabLabos.setTabText(self.tabLabos.indexOf(self.tabLabo1), _translate("Dialog", "Labo 1"))
        self.tabSeances.setTabText(self.tabSeances.indexOf(self.tabSeance1), _translate("Dialog", "Séance 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
